/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Niranjan
 */
public class bookReg extends javax.swing.JFrame {
    public Connection connection;
    public PreparedStatement pstmt;
    public ResultSet rs;
    public ResultSetMetaData rsmd;
    
    void initConnection(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            try{
                connection = DriverManager.getConnection("jdbc:oracle:thin:@DESKTOP-2U6J23R:1521:orcl","scott","tiger");
                System.out.println("Connected to the database");
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Connection Failed\n"+ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Driver not found\n"+ex.getMessage());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Unknown Error\n"+ex.getMessage());
        }
    }
    /**
     * Creates new form bookReg
     */
    public bookReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lang_br = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookid_br = new javax.swing.JTextField();
        title_br = new javax.swing.JTextField();
        publishdate_br = new javax.swing.JTextField();
        publisher_br = new javax.swing.JTextField();
        genre_br = new javax.swing.JTextField();
        type_br = new javax.swing.JTextField();
        reg_bt_br = new javax.swing.JButton();
        author_br1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Book ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, -1));
        jPanel1.add(lang_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 71, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel3.setText("Title");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel4.setText("Publisher_date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setText("Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel6.setText("Genre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel8.setText("Publisher");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel9.setText("Language");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        jPanel1.add(bookid_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 71, -1));

        title_br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title_brActionPerformed(evt);
            }
        });
        jPanel1.add(title_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 71, -1));
        jPanel1.add(publishdate_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 71, -1));
        jPanel1.add(publisher_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 71, -1));
        jPanel1.add(genre_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 71, -1));

        type_br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_brActionPerformed(evt);
            }
        });
        jPanel1.add(type_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 71, -1));

        reg_bt_br.setText("Register");
        reg_bt_br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_bt_brActionPerformed(evt);
            }
        });
        jPanel1.add(reg_bt_br, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        jPanel1.add(author_br1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 71, -1));

        jLabel10.setText("Author");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void title_brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_brActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_brActionPerformed

    private void type_brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_brActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_brActionPerformed

    private void reg_bt_brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_bt_brActionPerformed
        initConnection();
        String book_id=bookid_br.getText();
        String title=title_br.getText();
        String author=publishdate_br.getText();
        String publisher=publisher_br.getText();
        String genre=genre_br.getText();
        String type=type_br.getText(); 
        String language=lang_br.getText();
        String publisherdate = publishdate_br.getText();
        int flag=0;
        try
        {
            // Assuming you have a PreparedStatement object named pstmt
            String sql = "INSERT INTO books (book_id, title, author, language, publisher, type, genre,publisher_date) VALUES (?, ?, ?, ?, ?, ?, ?,?)";
            pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, book_id);
            pstmt.setString(2, title);
            pstmt.setString(3, author);
            pstmt.setString(4, language);
            pstmt.setString(5, publisher);
            pstmt.setString(6, type);
            pstmt.setString(7, genre);
            pstmt.setString(8, publisherdate);
            
            pstmt.executeUpdate();

        }
        catch (Exception e)
        {
            flag=1;
            e.printStackTrace();
        }
        if(flag==0)
        {
            home newHomePage = new home();
            newHomePage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_reg_bt_brActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        home newhome = new home();
        newhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField author_br1;
    private javax.swing.JTextField bookid_br;
    private javax.swing.JTextField genre_br;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lang_br;
    private javax.swing.JTextField publishdate_br;
    private javax.swing.JTextField publisher_br;
    private javax.swing.JButton reg_bt_br;
    private javax.swing.JTextField title_br;
    private javax.swing.JTextField type_br;
    // End of variables declaration//GEN-END:variables
}
