/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author NIKILESH
 */
public class LendBook extends javax.swing.JFrame {
    public Connection connection;
    public PreparedStatement pstmt;
    public ResultSet rs;
    public ResultSetMetaData rsmd;
    
      void initConnection(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            try{
                connection = DriverManager.getConnection("jdbc:oracle:thin:@DESKTOP-2U6J23R:1521:orcl","scott","tiger");
                System.out.println("Connected to the database");
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Connection Failed\n"+ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Driver not found\n"+ex.getMessage());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Unknown Error\n"+ex.getMessage());
        }
    }
    /**
     * Creates new form LendBook
     */
    public LendBook() {
        initComponents();
        initConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Submit_btn_lb = new javax.swing.JButton();
        Member_id = new javax.swing.JTextField();
        Bookid_lb1 = new javax.swing.JTextField();
        Datelent_lb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 344));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Book id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 71, 38));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Membership id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 132, 118, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Date lent");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 71, 38));

        Submit_btn_lb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Submit_btn_lb.setText("Submit");
        Submit_btn_lb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btn_lbActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_btn_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 294, 90, 33));

        Member_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Member_idFocusLost(evt);
            }
        });
        getContentPane().add(Member_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 155, 38));

        Bookid_lb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Bookid_lb1FocusLost(evt);
            }
        });
        getContentPane().add(Bookid_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 155, 38));

        Datelent_lb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Datelent_lbFocusLost(evt);
            }
        });
        getContentPane().add(Datelent_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 155, 38));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 295, -1, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_btn_lbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btn_lbActionPerformed
        String memid =Member_id.getText();
        String Bookid =Bookid_lb1.getText();
        String datelent = Datelent_lb.getText();
        
        try{
               String sql  = "insert into orders(bookid,memberid,lent_date) values (?,?,?)";
               pstmt = connection.prepareStatement(sql);
               pstmt.setString(1, Bookid);
               pstmt.setString(2, memid);
               pstmt.setString(3, datelent);
               pstmt.execute();
        }
        catch(Exception e){
            e.printStackTrace();
        }
                
    }//GEN-LAST:event_Submit_btn_lbActionPerformed

    private void Member_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Member_idFocusLost
        String memid =Member_id.getText();
        try
        {
            String sql = "select * from memberinfo where memberid= ?";
            pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, memid);
            rs = pstmt.executeQuery();

            if(!rs.next()){
                JOptionPane.showMessageDialog(this , "Member not found");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Member_idFocusLost

    private void Bookid_lb1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Bookid_lb1FocusLost
        String Bookid =Bookid_lb1.getText();
        try
        {
            String sql = "select * from books where book_id= ?";
            pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, Bookid);
            rs = pstmt.executeQuery();

            if(!rs.next()){
                JOptionPane.showMessageDialog(this , "book not found");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Bookid_lb1FocusLost

    private void Datelent_lbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Datelent_lbFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Datelent_lbFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        home hpage = new home();
        hpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LendBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bookid_lb1;
    private javax.swing.JTextField Datelent_lb;
    private javax.swing.JTextField Member_id;
    private javax.swing.JButton Submit_btn_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
