/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Niranjan
 */
public class memReg extends javax.swing.JFrame {
    public Connection connection;
    public PreparedStatement pstmt;
    public ResultSet rs;
    public ResultSetMetaData rsmd;
    
    void initConnection(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            try{
                connection = DriverManager.getConnection("jdbc:oracle:thin:@DESKTOP-2U6J23R:1521:orcl","scott","tiger");
                System.out.println("Connected to the database");
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Connection Failed\n"+ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Driver not found\n"+ex.getMessage());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Unknown Error\n"+ex.getMessage());
        }
    }
    /**
     * Creates new form memReg
     */
    public memReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_mr = new javax.swing.JTextField();
        phone_mr = new javax.swing.JTextField();
        email_mr = new javax.swing.JTextField();
        memtype_mr = new javax.swing.JTextField();
        reg_bt_mr = new javax.swing.JButton();
        address_mr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setText("Phone No.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel6.setText("Member Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        name_mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_mrActionPerformed(evt);
            }
        });
        jPanel1.add(name_mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 71, -1));
        jPanel1.add(phone_mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 71, -1));
        jPanel1.add(email_mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 71, -1));
        jPanel1.add(memtype_mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 71, -1));

        reg_bt_mr.setText("Register");
        reg_bt_mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_bt_mrActionPerformed(evt);
            }
        });
        jPanel1.add(reg_bt_mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));
        jPanel1.add(address_mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 71, -1));

        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_mrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_mrActionPerformed

    private void reg_bt_mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_bt_mrActionPerformed
        initConnection();
        String name=name_mr.getText();
        String address=address_mr.getText();
        String phone=phone_mr.getText();
        String email=email_mr.getText();
        String mem_type=memtype_mr.getText(); 
        int flag=0;
        try
        {
            // Assuming you have a PreparedStatement object named pstmt
            String sql = "INSERT INTO memberinfo (name, address, phone_no, email, member_type) VALUES (?, ?, ?, ?, ?)";
            pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, name);
            pstmt.setString(2, address);
            pstmt.setString(3, phone);
            pstmt.setString(4, email);
            pstmt.setString(5, mem_type);
            
            pstmt.executeUpdate();

        }
        catch (Exception e)
        {
            flag=1;
            e.printStackTrace();
        }
        if(flag==0)
        {
            home newHomePage = new home();
            newHomePage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_reg_bt_mrActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        home newhome = new home();
        newhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField address_mr;
    private javax.swing.JTextField email_mr;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField memtype_mr;
    private javax.swing.JTextField name_mr;
    private javax.swing.JTextField phone_mr;
    private javax.swing.JButton reg_bt_mr;
    // End of variables declaration//GEN-END:variables
}
