/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Niranjan
 */
public class SignUp extends javax.swing.JFrame {
    public Connection connection;
    public PreparedStatement pstmt;
    public ResultSet rs;
    public ResultSetMetaData rsmd;
    public int flag=0;
    
    void initConnection(){
        try{
            Class.forName("oracle.jdbc.OracleDriver");
            try{
                connection = DriverManager.getConnection("jdbc:oracle:thin:@DESKTOP-2U6J23R:1521:orcl","scott","tiger");
                System.out.println("Connected to the database");
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Connection Failed\n"+ex.getMessage());
            }
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Driver not found\n"+ex.getMessage());
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Unknown Error\n"+ex.getMessage());
        }
    }
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        initConnection();
    }
    
    public boolean validateSignUp()
    {
        String username=username_sp.getText();
        String pwd=password_sp.getText();
        String name=name_sp.getText();
        String phone=phone_sp.getText();
        String email=email_sp.getText();
        String role=role_sp.getText();
        if (username.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pls Enter Username");
            return false;
        }
        if (pwd.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pls Enter Password");
            return false;
        }
        if (name.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pls Enter name");
            return false;
        }
        if (phone.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pls Enter phone");
            return false;
        }
        if (email.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pls Enter email");
            return false;
        }
        if (role.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Pls Enter role");
            return false;
        }
        return true;
    }
    
    public void signUpPage()
    {
        String username=username_sp.getText();
        String pwd=password_sp.getText();
        String name=name_sp.getText();
        String phone=phone_sp.getText();
        String email=email_sp.getText();
        String role=role_sp.getText();
        try
        {
            // Assuming you have a PreparedStatement object named pstmt
            String sql = "INSERT INTO workers (username, password, name, role, phone_no, email) VALUES (?, ?, ?, ?, ?, ?)";
            pstmt = connection.prepareStatement(sql);
            pstmt.setString(1, username);
            pstmt.setString(2, pwd);
            pstmt.setString(3, name);
            pstmt.setString(4, role);
            pstmt.setString(5, phone);
            pstmt.setString(6, email);
            pstmt.executeUpdate();
            flag=0;

        }
        catch (Exception e)
        {
            e.printStackTrace();
            flag=1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        password_sp = new javax.swing.JTextField();
        username_sp = new javax.swing.JTextField();
        signup_bt_sp = new javax.swing.JButton();
        name_sp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email_sp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        role_sp = new javax.swing.JTextField();
        phone_sp = new javax.swing.JTextField();
        back_bt_sp = new javax.swing.JButton();
        signup_bt_lp4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setText("Management");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel2.setText("System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel3.setText("Library");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 440));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel7.setText("Management");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel8.setText("System");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel9.setText("Library");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 410));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel13.setText("Management");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 60));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel14.setText("System");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 60));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel15.setText("Library");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 60));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 410));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 102, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel18.setText("Management");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 60));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel19.setText("System");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 60));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel20.setText("Library");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 60));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 410));

        jLabel21.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        jLabel21.setText("Sign Up");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 140, 50));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel22.setText("Password");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel23.setText("Username");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));
        jPanel7.add(password_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 130, 30));

        username_sp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_spFocusLost(evt);
            }
        });
        jPanel7.add(username_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 130, 30));

        signup_bt_sp.setText("Sign Up");
        signup_bt_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_bt_spActionPerformed(evt);
            }
        });
        jPanel7.add(signup_bt_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));
        jPanel7.add(name_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel11.setText("Email");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        email_sp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_spFocusLost(evt);
            }
        });
        jPanel7.add(email_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel5.setText("Name");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel12.setText("Role");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel16.setText("Phone No.");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));
        jPanel7.add(role_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 130, 30));
        jPanel7.add(phone_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 130, 30));

        back_bt_sp.setText("Back");
        back_bt_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bt_spActionPerformed(evt);
            }
        });
        jPanel7.add(back_bt_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        signup_bt_lp4.setText("Sign Up");
        jPanel1.add(signup_bt_lp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_bt_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bt_spActionPerformed
        Login newLoginPage = new Login();
        newLoginPage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_back_bt_spActionPerformed

    private void signup_bt_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_bt_spActionPerformed
        if(validateSignUp())
        {
            signUpPage();
            if(flag==0)
            {
                Login newLoginPage = new Login();
                newLoginPage.setVisible(true);
                this.dispose();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_signup_bt_spActionPerformed

    private void username_spFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_spFocusLost
        String username=username_sp.getText(); 
        try
        {
            pstmt=connection.prepareStatement("Select username from workers where username=?");
            pstmt.setString(1,username);
            rs=pstmt.executeQuery();
            if (rs.next())
            {
                JOptionPane.showMessageDialog(this, "Username Already Exists");
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_username_spFocusLost

    private void email_spFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_spFocusLost
        String email=email_sp.getText(); 
        try
        {
            pstmt=connection.prepareStatement("Select email from workers where email=?");
            pstmt.setString(1,email);
            rs=pstmt.executeQuery();
            if (rs.next())
            {
                JOptionPane.showMessageDialog(this, "Email Already Exists");
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_email_spFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_bt_sp;
    private javax.swing.JTextField email_sp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField name_sp;
    private javax.swing.JTextField password_sp;
    private javax.swing.JTextField phone_sp;
    private javax.swing.JTextField role_sp;
    private javax.swing.JButton signup_bt_lp4;
    private javax.swing.JButton signup_bt_sp;
    private javax.swing.JTextField username_sp;
    // End of variables declaration//GEN-END:variables
}
